//! `~/.zshrc` / `~/.bashrc` muxad-autostart hook.
//!
//! Cross-platform fallback for systems with no service manager —
//! containers, BSDs, WSL1, minimal Linux. Adds a one-liner to the
//! user's primary shell rc that boots `muxad` if it isn't already
//! running. Wrapped in our standard `# >>> muxa managed (id) >>>`
//! marker block so `--uninstall` is surgical.
//!
//! Shell detection is **best-effort**: we read `$SHELL`, fall back
//! to zsh on macOS (Apple's default since Catalina) and bash on
//! Linux. If we guess wrong the user can override with the explicit
//! `--component muxad-shellrc:bash` form (not yet wired — TODO if
//! anyone ever needs it).

use crate::init::components::Component;
use crate::init::marker;
use crate::init::marker::Outcome;
use std::path::PathBuf;

/// The body that goes inside the marker block.
///
/// Notes on the choice of one-liner:
/// - `pgrep -x muxad` is in coreutils on Linux + macOS by default.
/// - `> /dev/null` silences output even when the process exists.
/// - `(nohup … &)` runs muxad detached so closing the shell that
///   started it doesn't take the daemon down. `2>&1` drops stderr
///   too because launching muxad on every new shell shouldn't paint
///   noise on the prompt.
/// - `disown` would be cleaner but isn't portable across all the
///   shells we hit (dash / ksh in some BSD setups). The `(...)`
///   subshell trick is shell-agnostic.
pub const HOOK_BODY: &str = r"# Auto-start muxad if it isn't running. Generated by `muxa init`.
if command -v muxad >/dev/null 2>&1 && ! pgrep -x muxad >/dev/null 2>&1; then
  (nohup muxad >/tmp/muxad.log 2>&1 &) >/dev/null 2>&1
fi";

/// Locate the user's primary shell rc file. Falls back to
/// `~/.profile` if neither $SHELL nor the well-known names yield a
/// hit — at least `~/.profile` is portable.
pub fn default_path() -> Option<PathBuf> {
    let home = dirs::home_dir()?;
    if let Some(p) = preferred_rc_for(&std::env::var("SHELL").unwrap_or_default(), &home) {
        return Some(p);
    }
    // Existing-file fallback: pick whichever of zshrc / bashrc the
    // user actually has, otherwise create ~/.profile.
    let zshrc = home.join(".zshrc");
    let bashrc = home.join(".bashrc");
    if zshrc.is_file() {
        return Some(zshrc);
    }
    if bashrc.is_file() {
        return Some(bashrc);
    }
    Some(home.join(".profile"))
}

fn preferred_rc_for(shell_env: &str, home: &std::path::Path) -> Option<PathBuf> {
    let shell = std::path::Path::new(shell_env)
        .file_name()
        .and_then(|s| s.to_str())
        .unwrap_or("");
    match shell {
        "zsh" => Some(home.join(".zshrc")),
        "bash" => Some(home.join(".bashrc")),
        "fish" => Some(home.join(".config/fish/config.fish")),
        _ => None,
    }
}

pub fn upsert(original: &str) -> (String, Outcome) {
    marker::upsert(original, Component::MuxadShellrc.id(), HOOK_BODY)
}

pub fn remove(original: &str) -> (String, Outcome) {
    marker::remove(original, Component::MuxadShellrc.id())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn upsert_round_trip() {
        let (after, o1) = upsert("");
        assert_eq!(o1, Outcome::Inserted);
        assert!(after.contains("pgrep -x muxad"));
        assert!(after.contains("muxa managed (muxad-shellrc)"));

        let (after2, o2) = upsert(&after);
        assert_eq!(o2, Outcome::Unchanged);
        assert_eq!(after, after2);

        let (after3, o3) = remove(&after2);
        assert_eq!(o3, Outcome::Removed);
        assert!(!after3.contains("pgrep -x muxad"));
    }

    #[test]
    fn upsert_preserves_user_rc_around_block() {
        let user = "export PATH=/foo:$PATH\nalias ll='ls -la'\n";
        let (after, _) = upsert(user);
        assert!(after.contains("export PATH=/foo:$PATH"));
        assert!(after.contains("alias ll='ls -la'"));
        assert!(after.contains("pgrep -x muxad"));
    }

    #[test]
    fn preferred_rc_picks_per_shell() {
        let home = std::path::Path::new("/home/test");
        assert_eq!(
            preferred_rc_for("/bin/zsh", home),
            Some(home.join(".zshrc"))
        );
        assert_eq!(
            preferred_rc_for("/usr/bin/bash", home),
            Some(home.join(".bashrc"))
        );
        assert_eq!(
            preferred_rc_for("/usr/local/bin/fish", home),
            Some(home.join(".config/fish/config.fish"))
        );
        // Unknown shells don't presume — caller falls through.
        assert_eq!(preferred_rc_for("/bin/dash", home), None);
        assert_eq!(preferred_rc_for("", home), None);
    }
}
